; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; Nom du projet : Dev-Type
; Nom du fichier : DevType - Window.pb
; Version du fichier : 1.0.0
; Programmation : OK
; Programmé par : Guillaume
; Alias : Guimauve
; Courriel : gsaumure79@videotron.ca
; Date : 28-04-2008
; Mise à jour : 30-01-2009
; Codé pour PureBasic V4.40
; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; AUTOMATICALLY GENERATED CODE, DO NOT MODIFY
; UNLESS YOU REALLY,REALLY, REALLY MEAN IT !!
; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; Code generated by : Dev-Type V3.0.0
; Project name : the project name here
; File name : File name here
; File Version : 0.0.0
; Programmation : In progress
; Programmed by : Your name here
; AKA : Your NickName here
; E-mail : address@something.com
; Creation Date : 13-09-2011
; Last update : 13-09-2011
; Coded for PureBasic V4.60
; Platform : Windows, Linux, MacOS X
; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< Structure declaration <<<<<

Structure Window

  PosX.w
  PosY.w
  Width.w
  Height.w

EndStructure

; <<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< The observators <<<<<

Macro GetWindowPosX(WindowA)

  WindowA\PosX

EndMacro

Macro GetWindowPosY(WindowA)

  WindowA\PosY

EndMacro

Macro GetWindowWidth(WindowA)

  WindowA\Width

EndMacro

Macro GetWindowHeight(WindowA)

  WindowA\Height

EndMacro

; <<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< The mutators <<<<<

Macro SetWindowPosX(WindowA, P_PosX)

  GetWindowPosX(WindowA) = P_PosX

EndMacro

Macro SetWindowPosY(WindowA, P_PosY)

  GetWindowPosY(WindowA) = P_PosY

EndMacro

Macro SetWindowWidth(WindowA, P_Width)

  GetWindowWidth(WindowA) = P_Width

EndMacro

Macro SetWindowHeight(WindowA, P_Height)

  GetWindowHeight(WindowA) = P_Height

EndMacro

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< The Update operator <<<<<

Macro UpdateWindow(WindowA, P_PosX, P_PosY, P_Width, P_Height)

  SetWindowPosX(WindowA, P_PosX)
  SetWindowPosY(WindowA, P_PosY)
  SetWindowWidth(WindowA, P_Width)
  SetWindowHeight(WindowA, P_Height)

EndMacro

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< The Reset operator <<<<<

Macro ResetWindow(WindowA)
  
  SetWindowPosX(WindowA, 0)
  SetWindowPosY(WindowA, 0)
  SetWindowWidth(WindowA, 0)
  SetWindowHeight(WindowA, 0)
  
EndMacro

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< Read preferences group <<<<<

Procedure ReadPreferenceWindow(GroupName.s, *WindowA.Window)

  PreferenceGroup(GroupName)
  
  SetWindowPosX(*WindowA, ReadPreferenceLong("PosX", GetWindowPosX(*WindowA)))
  SetWindowPosY(*WindowA, ReadPreferenceLong("PosY", GetWindowPosY(*WindowA)))
  ; SetWindowWidth(*WindowA, ReadPreferenceLong("Width", GetWindowWidth(*WindowA)))
  ; SetWindowHeight(*WindowA, ReadPreferenceLong("Height", GetWindowHeight(*WindowA)))
  
EndProcedure

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< Write preferences group <<<<<

Procedure WritePreferenceWindow(GroupName.s, *WindowA.Window)

  PreferenceGroup(GroupName)
  
  WritePreferenceLong("PosX", GetWindowPosX(*WindowA))
  WritePreferenceLong("PosY", GetWindowPosY(*WindowA))
  ; WritePreferenceLong("Width", GetWindowWidth(*WindowA))
  ; WritePreferenceLong("Height", GetWindowHeight(*WindowA))
  
EndProcedure

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< Code generated in : 00.009 seconds (15333.33 lines/second) <<<<<
; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< The CreateWindow Operator <<<<<

Macro CreateWindow(WinID, WindowA, Title = "", Flag = #PB_Window_SystemMenu)
  
  OpenWindow(WinID, GetWindowPosX(WindowA), GetWindowPosY(WindowA), GetWindowWidth(WindowA), GetWindowHeight(WindowA), Title, Flag)
  
EndMacro

Macro CreateWindowEx(WinID, WindowA, Title, Flag, ParentID)
  
  OpenWindow(WinID, GetWindowPosX(WindowA), GetWindowPosY(WindowA), GetWindowWidth(WindowA), GetWindowHeight(WindowA), Title, Flag, ParentID)
  
EndMacro

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< The GetWindowCurrentPosition Operator <<<<<

Macro GetWindowCurrentPosition(WinID, WindowA)
  
  SetWindowPosX(WindowA, WindowX(WinID))
  SetWindowPosY(WindowA, WindowY(WinID))
  SetWindowWidth(WindowA, WindowWidth(WinID))
  SetWindowHeight(WindowA, WindowHeight(WinID))
  
EndMacro

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< The Update operator <<<<<

Procedure InitializeWindow(*WindowA.Window)

  SetWindowPosX(*WindowA, 100)
  SetWindowPosY(*WindowA, 100)
  SetWindowWidth(*WindowA, 800)
  SetWindowHeight(*WindowA, 600)

EndProcedure

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< The Verify Window Position Operator <<<<<

Procedure VerifyWindowPosition(*WindowA.Window)
  
  If ExamineDesktops()
    
    If GetWindowPosX(*WindowA) > DesktopWidth(0) Or GetWindowPosX(*WindowA) < 0
      SetWindowPosX(*WindowA, 100)
    EndIf
    
    If GetWindowPosY(*WindowA) > DesktopHeight(0) Or GetWindowPosY(*WindowA) < 0
      SetWindowPosY(*WindowA, 100)
    EndIf
    
    If (GetWindowPosX(*WindowA) + GetWindowWidth(*WindowA)) > DesktopWidth(0)
      SetWindowPosX(*WindowA, GetWindowPosX(*WindowA) - GetWindowWidth(*WindowA))
    EndIf
    
    If (GetWindowPosY(*WindowA) + GetWindowHeight(*WindowA)) > DesktopHeight(0)
      SetWindowPosY(*WindowA, GetWindowPosY(*WindowA) - GetWindowHeight(*WindowA))
    EndIf
    
  Else 
    
    SetWindowPosX(*WindowA, 100)
    SetWindowPosY(*WindowA, 100)
    
  EndIf
  
EndProcedure

; <<<<<<<<<<<<<<<<<<<<<<<
; <<<<< END OF FILE <<<<<
; <<<<<<<<<<<<<<<<<<<<<<<
; IDE Options = PureBasic 4.60 RC 1 (Linux - x64)
; CursorPosition = 162
; FirstLine = 129
; Folding = ----
; EnableXP